package me.makkuusen.timing.system.tuning;

public enum Attribute {
    FORWARD_ACCEL,
    YAW_ACCEL,
    DEFAULT_SLIPPERINESS,
    PACKED_ICE_SLIPPERINESS,
    BLUE_ICE_SLIPPERINESS,
    TURNING_FORWARD_ACCEL,
    BACKWARD_ACCEL,
    SCALE,
    MAX_SPEED,
    MAX_SPEED_RESISTANCE,
    BRAKE_SLIPPERINESS,
    LATERAL_SLIPPERINESS,
    WALLTAP_MULTIPLIER,
}
